export const Fonts = {
  Bold: 'RobotoCondensed-Bold',
  Black: 'RobotoCondensed-Black',
  BlackItalic: 'RobotoCondensed-BlackItalic',
  BoldItalic: 'RobotoCondensed-BoldItalic',
  ExtraBold: 'RobotoCondensed-ExtraBold',
  ExtraBoldItalic: 'RobotoCondensed-ExtraBoldItalic',
  ExtraLight: 'RobotoCondensed-ExtraLight',
  ExtraLightItalic: 'RobotoCondensed-ExtraLightItalic',
  Italic: 'RobotoCondensed-Italic',
  Light: 'RobotoCondensed-Light',
  LightItalic: 'RobotoCondensed-LightItalic',
  Medium: 'RobotoCondensed-Medium',
  MediumItalic: 'RobotoCondensed-MediumItalic',
  Regular: 'RobotoCondensed-Regular',
  SemiBold: 'RobotoCondensed-SemiBold',
  SemiBoldItalic: 'RobotoCondensed-SemiBoldItalic',
  Thin: 'RobotoCondensed-Thin',
  ThinItalic: 'RobotoCondensed-ThinItalic',
};
